# params.yaml - Defines parameters for model training and experiments

# Data Parameters

# Path to the dataset
data:
  path: "artifacts/Important_features_data.csv"
  test_size: 0.2
  random_state: 42

# Model Parameters
model:
  xgboost:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.01
  random_forest:
    n_estimators: 100
    max_depth: 10

# Training Parameters
training:
  batch_size: 32
  epochs: 20
  early_stopping_rounds: 10

# Evaluation Parameters
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
  cross_validation_folds: 3
