# params.yaml - Defines parameters for model training and experiments

# Data Parameters

# Path to the dataset
data:
  path: "artifacts/Important_features_data.csv"
  test_size: 0.2
  random_state: 42

# Model Parameters
model:
  xgboost:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.01
  lightgbm:
    n_estimators: 100
    max_depth: 4
    learning_rate: 0.2
    force_col_wise: True
  CatBoost:
    n_estimators: 100
    iterations:100
    learning_rate: 0.2
    verbose: 0
  AdaBoost:
    n_estimators: 100
    learning_rate: 1.0
    random_state:42

# Training Parameters
xgboost':
    max_depth: [3, 4, 5]
    learning_rate: [0.1, 0.2, 0.3]
    n_estimators: [50, 100, 200]
    
    lightgbm: 
    max_depth: [3, 4, 5]
    learning_rate: [0.05, 0.1, 0.2]
    n_estimators: [50, 100, 150]
    
    catboost:
    iterations: [100, 150]
    learning_rate: [0.1, 0.2]
    depth: [3, 4, 5]
    
    adaboost:
    learning_rate: [0.5, 1.0, 1.5]
    n_estimators: [50, 100, 150]
    algorithm: ['SAMME', 'SAMME.R']  # Trying both AdaBoost algorithms
    random_state: [42]


# Evaluation Parameters
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
  cross_validation_folds: 3
